// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Active-navController from "./active-nav_controller"
application.register("active-nav", Active-navController)

import CarouselController from "./carousel_controller"
application.register("carousel", CarouselController)

import Disappear-homeController from "./disappear-home_controller"
application.register("disappear-home", Disappear-homeController)

import Hover-imagesController from "./hover-images_controller"
application.register("hover-images", Hover-imagesController)

import RefreshListController from "./refresh_list_controller"
application.register("refresh-list", RefreshListController)

import ScrollController from "./scroll_controller"
application.register("scroll", ScrollController)

import Switch-tabController from "./switch-tab_controller"
application.register("switch-tab", Switch-tabController)
