meta_product_name: "Les Jardins d'Alice"
meta_title: "Les Jardins d'Alice - Herboristerie et agriculture bio en pays niçois"
meta_description: "Les Jardins d'Alice, ce sont 2 lieux, l'un en montagne, à Beuil, et l'autre en vallée, à Cantaron. Depuis 2016, j'y développe des cueillettes et cultures de plantes médicinales bio principalement.
                  Je propose une gamme de produits naturels et certifiés en agriculture biologique, à base de plantes. Tisanes, hydrolats, huiles essentielles et aromatiques, confitures, sirops et fruits déshydratés,
                  tous proviennent de ma région, les alpes-maritimes, et de la graine jusqu’à l’étiquette, tous mes produits sont fait par mes petites mains!"
meta_image: "cover.png"
